name: Build container image
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    paths:
      - .github/workflows/build-image.yml
      - Dockerfile
permissions:
  contents: read
  packages: write

jobs:
  compute-suffix:
    runs-on: ubuntu-latest
    steps:
      - id: version_vars
        env:
          TZ: Etc/UTC
        run: |
          echo mastodon_version_prerelease=nightly.$(date +'%Y-%m-%d')>> $GITHUB_OUTPUT
    outputs:
      prerelease: ${{ steps.version_vars.outputs.mastodon_version_prerelease }}

  build-image:
    needs: compute-suffix
    uses: ./.github/workflows/build-container-image.yml
    with:
      platforms: linux/amd64,linux/arm64
      use_native_arm64_builder: true
      cache: false
      push_to_images: |
        brsu/mastodon
        ghcr.io/Brsu148/mastodon
#      version_prerelease: ${{ needs.compute-suffix.outputs.prerelease }}
      labels: ${{ needs.compute-suffix.outputs.prerelease }}
      flavor: |
        latest=auto
      tags: |
        type=edge,branch=main
        type=raw,value=edge
        type=ref,event=pr
#        type=schedule,pattern=${{ needs.compute-suffix.outputs.prerelease }}
    secrets: inherit
